services:
  # 1. Backend API (Express)
  - type: web
    name: musically-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musically-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: musically-redis
          property: connectionString

      - key: JWT_SECRET
        generateValue: true

      - key: NODE_ENV
        value: production

      - key: ALLOW_ALL_ORIGINS
        value: "true"

  # 2. Frontend (Next.js)
  - type: web
    name: musically-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_HOST
        fromService:
          type: web
          name: musically-api
          property: host

      - key: NEXT_PUBLIC_SOCKET_HOST
        fromService:
          type: web
          name: musically-api
          property: host

databases:
  # 4. Postgres
  - name: musically-db
    plan: free
    region: oregon
